### ISSUE TITLE
Pytest 7 breaks several plugins

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#57]
Pytest 7 deprecated the use of its own path objects, causing several plugins to start to raise deprecation warnings:

- [x] pytest-perf (jaraco/pytest-perf#5)
- [ ] pytest-flake8 (https://github.com/tholo/pytest-flake8/issues/83)
- [ ] pytest-black (https://github.com/shopkeep/pytest-black/issues/55)
- [ ] pytest-mypy (https://github.com/dbader/pytest-mypy/issues/131)

**Comment by jaraco** [comment]
I realize now that the ignores added don't work on `pytest<7` because the warning doesn't exist to be ignored and fails with this error:

```
python run-test: commands[0] | pytest -p no:dist -p no:cov -k test_egg_info
Traceback (most recent call last):
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/pluggy/_callers.py", line 34, in _multicall
    next(gen)  # first yield
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/warnings.py", line 136, in pytest_load_initial_conftests
    with catch_warnings_for_item(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/warnings.py", line 52, in catch_warnings_for_item
    apply_warning_filters(config_filters, cmdline_filters)
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1603, in apply_warning_filters
    warnings.filterwarnings(*parse_warning_filter(arg, escape=False))
  File "/Users/jaraco/code/public/pypa/setuptools/.tox/python/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1579, in parse_warning_filter
    category: Type[Warning] = warnings._getcategory(category_)  # type: ignore[attr-defined]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/warnings.py", line 266, in _getcategory
    raise _OptionError("unknown warning category: %r" % (category,)) from None
warnings._OptionError: unknown warning category: 'pytest.PytestRemovedIn8Warning'
ERROR: InvocationError for command /Users/jaraco/code/public/pypa/setuptools/.tox/python/bin/pytest -p no:dist -p no:cov -k test_egg_info (exited with code 1)
```

**Comment by jaraco** [comment]
Addressing that concern in https://github.com/pytest-dev/pytest/discussions/9616.
